apiVersion: v1
kind: Namespace
metadata:
  name: my-eclipse-che
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-eclipse-che
spec:
  targetNamespaces:
  - my-eclipse-che
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-eclipse-che
  namespace: my-eclipse-che
spec:
  channel: stable
  name: eclipse-che
  source: operatorhubio-catalog
  sourceNamespace: olm


apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  uid: b8f56c10-d46c-40d9-8bfa-c4db9707c246
spec:
  channel: stable
  installPlanApproval: Automatic
  name: eclipse-che
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: eclipse-che.v7.13.2
